### ISSUE TITLE
Students by Academic Program Dashboard Graph

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#102]
The graphs on the Dashboard are extremely helpful and we use them for reports all the time.  I'd like to request that Students by Academic Program graph reflect the active students only, just like the Gender by Academic Departments. I assume that the info is pulled from the sacp screen.  If so, could it pull Active programs from Active students.  Thanks!

**Comment by nomadicjosh** [comment]
I believe that is what it's already doing. Below is the query:

```mysql
SELECT COUNT(student.stuID) as count
FROM student
JOIN sacp ON student.stuID = sacp.stuID
WHERE student.status = 'A'
AND sacp.currStatus = 'A'
```

Can you tell me what you believe to be the true number vs. what the graph shows?

**Comment by BereaSchool** [comment]
That query looks correct, but that's not what the graph is showing. In our particular graph it shows programs that our active students are no longer enrolled in (old programs we have dissolved) such as DEBA, CEM.CMT, CEM.CMP, etc. None of our active students are enrolled in these.

**Comment by nomadicjosh** [comment]
Attached is a screenshot of what I see. It is from the SACP table.

<img width="305" alt="Screen Shot 2019-07-15 at 6 44 41 PM" src="https://user-images.githubusercontent.com/2042176/61253915-bd6fcb80-a730-11e9-9a1a-836ce82cac17.png">

**Comment by BereaSchool** [comment]
I revise my remarks. I ran your query and the programs on the graph that are not present in our active students are DEBA, ESP, CEM.CMM.  But our ABS and AU students don't even show up in the graph.

**Comment by nomadicjosh** [comment]
Sorry, wrong query. This is the right one.

```mysql
SELECT COUNT(sacp.id) AS Count,sacp.acadProgCode AS Prog
FROM sacp
JOIN acad_program b ON sacp.acadProgCode = b.acadProgCode
JOIN student ON sacp.stuID = student.stuID
WHERE sacp.currStatus <> 'G'
AND sacp.currStatus <> 'C'
AND student.status = 'A'
GROUP BY sacp.acadProgCode
ORDER BY sacp.acadProgCode DESC
LIMIT 10
```

I will remove the limit clause, but if it causes issues down the road, I will need to place the limit back.

**Comment by BereaSchool** [comment]
If you can remove the 'G' and 'C' and only show student.status = 'A' and sacp.currStatus 'A' —That will give us a more accurate picture.

**Comment by nomadicjosh** [comment]
The hairpin symbol ( <> ) means _not equal to_.

**Comment by BereaSchool** [comment]
Thank you for explaining the hairpin, but it now makes things even more mysterious.  Because our graph is still pulling DEBA, ESP, CEM.CMM and CEM.CMMP are not current active students. Those programs do not exist any longer.

**Comment by BereaSchool** [comment]
I think I see the problem.  It is pulling all 'W' and 'P' statuses.  If you run the query as I modified it below, it should pull the correct information:

SELECT COUNT(sacp.id) AS Count,sacp.acadProgCode AS Prog
FROM sacp
JOIN acad_program b ON sacp.acadProgCode = b.acadProgCode
JOIN student ON sacp.stuID = student.stuID
WHERE sacp.currStatus = 'A'
AND student.status = 'A'
GROUP BY sacp.acadProgCode
ORDER BY sacp.acadProgCode DESC

**Comment by BereaSchool** [comment]
Have you been able to update the query?

**Comment by nomadicjosh** [comment]
Should be fixed now.

**Comment by BereaSchool** [comment]
Excellent! Thank you!
