### ISSUE TITLE
Application

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#109]
We have trying to receive applications, however, every time an applicant presses submit, a red 'error conflict' message appears.  Please help!

**Comment by BereaSchool** [comment]
We are in **emergency mode** because we realized that there is no way to «create student» without an active application. We attempted backend by creating a profile using (APER).  We can create a staff record, but not a student record.  This is an issue you may need to address in the future.

Meanwhile, since APPL is the only way to enter applicant information in order to «create student» we need this to function.  I've added a screenshot of the error we are receiving. It's a 409 error conflict message.  Please help!

![image](https://user-images.githubusercontent.com/35111092/72690388-f5920580-3ae9-11ea-9400-bf641f8440dd.png)

**Comment by BereaSchool** [comment]
Once this issue is resolved, we will need your help to manually create applications for 4 new applicants.  We did a backend and created their profiles through the NAE screen.  So they have person profiles, but no applications, and no way to create SPROs.  Please advise.

**Comment by nomadicjosh** [comment]
Sorry about this. I never received an email about this issue. I've fixed it, and tested the application process on the frontend as well as the backend, and it works. If you have any issues, please let me know. To create an application for persons already created, you should now see it under the actions column when you do a person lookup. Also, when you are on the edit screen of NAE, you will see the application icon (please see screenshot). Once the application has been created, then you can STU them.

<img width="358" alt="Screen Shot 2020-01-23 at 10 13 34 PM" src="https://user-images.githubusercontent.com/2042176/73046135-192cb700-3e2e-11ea-9bed-677a1ebd2b44.png">

**Comment by BereaSchool** [comment]
Thank you very much!
