### ISSUE TITLE
Payments posting on Student's bill

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#111]
I've been informed by staff of another issue with student bills. Under «Payments» the student's payments are missing the 'form' of payment and any check numbers.  Although staff enters the information, it will not populate on payment screen.  See screenshot.  Thank you!
![Screen Shot 2020-01-24 at 12 50 31 AM](https://user-images.githubusercontent.com/35111092/73047440-c5c56380-3e43-11ea-97f8-ebb1dd4e1c6f.png)

**Comment by nomadicjosh** [comment]
Can I get a student ID where this issue is found? Thanks

**Comment by BereaSchool** [comment]
All of them. But random example is 1526. She made two cash payments.

**Comment by nomadicjosh** [comment]
Form of payment is fixed, but I don't see issue with the check number field. I've viewed several payments for 1331 and see that field populated. If there is still an issue, please let me know.

**Comment by BereaSchool** [comment]
This is fixed. Thank you!!!
