### ISSUE TITLE
Cancellation of TinyMCE

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#113]
Hello Josh,
We are receiving the message below in our editors that TinyMCE will expire in February.  We do not want to lose information attached to our courses. Please advise how to proceed or how to renew the TinyMCE editor.  Thank you!

![Screen Shot 2021-01-21 at 9 05 05 PM](https://user-images.githubusercontent.com/35111092/105436049-7b302000-5c2c-11eb-8925-8ac608a27bfa.png)

**Comment by nomadicjosh** [comment]
The information will not be lost. I think it is a matter of upgrading to a newer version. I will take a look and make the needed changes.

**Comment by nomadicjosh** [comment]
This should be fixed now. Please clear your browser cache. If there are still issues, please let me know.

**Comment by BereaSchool** [comment]
Thanks so much. It is fixed.
