### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by psmithard** [parkerj/eduTrac-SIS#116]
Hi Josh,

I hope you are well in these "interesting" times!

I have an issue with SSL. When I zip into cPanel and enable https, all of the formatting disappears, as if the css files are not loading. Any ideas?

Best wishes,

Paul.

**Comment by nomadicjosh** [comment]
Yes, interesting times indeed, and it has put me way behind schedule. I am trying hard to catch up. In `app/dropins`, create a file called `ssl.dropin.php`. In the that file, make sure to have the following:

```php
<?php

$app = \Liten\Liten::getInstance();

function enable_force_url_ssl()
{
    $app = \Liten\Liten::getInstance();
    $domain = str_replace('http://', '', url('/'));
    $url = 'https://' . $domain;

    if ($app->req->server['SERVER_PORT'] != 443) {
        $https = rtrim($url, '/');
        redirect($https . $app->req->server['REQUEST_URI']);
        exit();
    }
    return $url;
}
$app->hook->add_filter('base_url', 'enable_force_url_ssl');
```
This should force a sitewide SSL.
