### ISSUE TITLE
Instructor not appear

### ISSUE THREAD

**Issue by gimesierra** [parkerj/eduTrac-SIS#59]
Hi. I want to know what are the steps to follow to be able to associate a teacher in a course section.
Because when I want to look for it in the instructor option, it does not appear.

![image](https://user-images.githubusercontent.com/36938392/36948119-6a0e09de-1fb4-11e8-9186-5ca32caec975.png)

**Comment by nomadicjosh** [comment]
The teacher must have a staff record.
