### ISSUE TITLE
Registrar email

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#61]
We have this email address «registros@bereaschool.org» as the registrar email address, however, our register reports that new class registrations are not arriving by email.  Could you check?  Thank you!

**Comment by nomadicjosh** [comment]
Do you have a test student in the system?

**Comment by BereaSchool** [comment]
Yes we do. #1341

**Comment by nomadicjosh** [comment]
This should be fixed now.

**Comment by BereaSchool** [comment]
Thank you!
