### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by planart** [parkerj/eduTrac-SIS#62]
Hello. After installed eduTrac-SIS-r6.3.4 - with some problems for the 0000-00-00 date in mysql and solved with the sql-mode="" - I have completed the initial script to populate the DB.
After that the page load give me server error 500.
No log appear in PROD mode in app/tmp/logs/, and in DEV mode no error appear on the screen.
A phpinfo.php file work correctly in the root.
I have verified also the permission, the mod_rewrite condition and reinstalled the solution again.
I'm running on a Linux Mint 18.3 with Apache 2, MySQL 5.7 and PHP 7
No solution for me or any help?
Thanks

**Comment by nomadicjosh** [comment]
Have you checked your server error logs?

**Comment by planart** [comment]
Hello Mr Parker, thanks for your immediate reply.
Yes, every time I try to load the page, Apache's error log give me some substantial error via PHP. 
Below is the sequence of messages for an access.
<details> 
  <summary>There is an Error Log?</summary>
   Apache Error Log: `[Mon Mar 19 17:42:32.002667 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/rlde.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.002881 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.003050 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.003078 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/CoreDatabase.php on line 141
[Mon Mar 19 17:42:32.003166 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/alst.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.003228 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.003486 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.003515 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Config.php on line 42
[Mon Mar 19 17:42:32.003535 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Validate.php on line 132
[2018-03-19 17:42:32] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "alst" {"NodeQ":"alst"} []
[Mon Mar 19 17:42:32.016535 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.016575 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/CoreDatabase.php on line 141
[Mon Mar 19 17:42:32.016672 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/stld.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.016723 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.016803 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.016828 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Config.php on line 42
[Mon Mar 19 17:42:32.016849 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Validate.php on line 132
[2018-03-19 17:42:32] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "stld" {"NodeQ":"stld"} []
[Mon Mar 19 17:42:32.017114 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.017161 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/CoreDatabase.php on line 141
[Mon Mar 19 17:42:32.017240 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/clvr.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.017291 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.017362 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.017385 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Config.php on line 42
[Mon Mar 19 17:42:32.017406 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Validate.php on line 132
[2018-03-19 17:42:32] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "clvr" {"NodeQ":"clvr"} []
[Mon Mar 19 17:42:32.017604 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.017627 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/CoreDatabase.php on line 141
[Mon Mar 19 17:42:32.017707 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/rrsr.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.017757 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_put_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 17:42:32.017827 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.017850 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Config.php on line 42
[Mon Mar 19 17:42:32.017870 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/Validate.php on line 132
[2018-03-19 17:42:32] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "rrsr" {"NodeQ":"rrsr"} []
[Mon Mar 19 17:42:32.018062 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 17:42:32.018086 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/NodeQ/CoreDatabase.php on line 141
[2018-03-19 17:42:32] error.ERROR: IOSTATE[403]: Forbidden: The following directory could not be created: /www/files/cache [] []
[Mon Mar 19 17:42:32.096415 2018] [:error] [pid 5928] [client RemoteIP:59735] PHP Fatal error:  Uncaught app\\src\\Core\\Exception\\IOException 'Could not create the file cache directory.' in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/Cache/etsis_Cache_Filesystem.php(166)\n#0 /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/Cache/etsis_Object_Cache.php(42): app\\src\\Core\\Cache\\etsis_Cache_Filesystem->__construct()\n#1 /var/www/html/eduTrac-SIS-r6.3.4/app/functions/global-function.php(26): app\\src\\Core\\Cache\\etsis_Object_Cache->__construct('file')\n#2 /var/www/html/eduTrac-SIS-r6.3.4/app/functions/cache-function.php(60): _etsis_cache_init()\n#3 /var/www/html/eduTrac-SIS-r6.3.4/app/src/Hooks.php(819): etsis_cache_get('system_email', 'option')\n#4 /var/www/html/eduTrac-SIS-r6.3.4/app/functions/logger-function.php(74): app\\src\\Hooks->get_option('system_email')\n#5 /var/www/html/eduTrac-SIS-r6.3.4/app/functions/dependency.php(693): require('/var/www/html/e...')\n#6 /var/www/html/eduTrac-SIS-r6.3.4/config.php(126): require('/var/www/html/e...')\n#7 /var/www/html/eduTrac-SIS-r6.3.4/index.php(27): include('/var/www/html/e...')\n#8 {main}\n  thrown in /var/www/html/eduTrac-SIS-r6.3.4/app/src/Core/Cache/etsis_Cache_Filesystem.php on line 166

`
</details>

**Comment by nomadicjosh** [comment]
Create a new directory and name it `etsis_tmp` (/var/www/etsis_tmp/). Open config.php, and change the following two lines:

```
    'cookies.savepath' => ini_get('session.save_path') . DS . $subdomain . DS,
    'file.savepath' => ini_get('session.save_path') . DS . $subdomain . DS . 'files' . DS
```

to look like this:

```
    'cookies.savepath' => '/var/www/etsis_tmp' . DS . $subdomain . DS,
    'file.savepath' => '/var/www/etsis_tmp' . DS . $subdomain . DS . 'files' . DS
```

If you still get errors, make sure your server can read and write to the `etsis_tmp` directory.

**Comment by planart** [comment]
Thanks
I had already made the directory in /var/www/html/eduTrac/etsis_tmp/ then executed a chmod -R 777 in it, before the log posted above.
In any case I have performed the recommended procedure

> $app = new \Liten\Liten(
    [
    'cookies.lifetime' => '86400',
    'cookies.savepath' => ini_get('/var/www/etsis_tmp') . DS . $subdomain . DS,
    'file.savepath' => ini_get('/var/www/etsis_tmp') . DS . $subdomain . DS . 'files' . DS
    ]
);

with write permission for everyone

> ls -lha /var/www/etsis_tmp/
drwxrwxrwx 2 root root 4,0K mar 19 21:43 .
drwxr-xr-x 4 root root 4,0K mar 19 21:43 ..

and this is the result:
<details>
<summary>Error Log</summary>
<p>"Apache Error Log `[Mon Mar 19 21:47:31.903129 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  file_put_contents(/www/nodes/etsis/rrsr.data.node): failed to open stream: No such file or directory in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 21:47:31.903184 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  file_put_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/File.php on line 66
[Mon Mar 19 21:47:31.903286 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 21:47:31.903314 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  array_keys() expects parameter 1 to be array, null given in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/Config.php on line 42
[Mon Mar 19 21:47:31.903336 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  in_array() expects parameter 2 to be array, null given in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132
[2018-03-19 21:47:31] error.ERROR: NODEQSTATE[0]: Field rule does not exists in node "rrsr" {"NodeQ":"rrsr"} []
[Mon Mar 19 21:47:31.903580 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  file_get_contents(/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/eduTrac/app/src/Core/NodeQ/Helpers/File.php on line 61
[Mon Mar 19 21:47:31.903607 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/eduTrac/app/src/Core/NodeQ/CoreDatabase.php on line 141
[2018-03-19 21:47:31] error.ERROR: IOSTATE[403]: Forbidden: The following directory could not be created: /www/files/cache [] []
[Mon Mar 19 21:47:31.946075 2018] [:error] [pid 5977] [client RemoteIP:62937] PHP Fatal error:  Uncaught app\\src\\Core\\Exception\\IOException 'Could not create the file cache directory.' in /var/www/html/eduTrac/app/src/Core/Cache/etsis_Cache_Filesystem.php(166)\n#0 /var/www/html/eduTrac/app/src/Core/Cache/etsis_Object_Cache.php(42): app\\src\\Core\\Cache\\etsis_Cache_Filesystem->__construct()\n#1 /var/www/html/eduTrac/app/functions/global-function.php(26): app\\src\\Core\\Cache\\etsis_Object_Cache->__construct('file')\n#2 /var/www/html/eduTrac/app/functions/cache-function.php(60): _etsis_cache_init()\n#3 /var/www/html/eduTrac/app/src/Hooks.php(819): etsis_cache_get('system_email', 'option')\n#4 /var/www/html/eduTrac/app/functions/logger-function.php(74): app\\src\\Hooks->get_option('system_email')\n#5 /var/www/html/eduTrac/app/functions/dependency.php(693): require('/var/www/html/e...')\n#6 /var/www/html/eduTrac/config.php(126): require('/var/www/html/e...')\n#7 /var/www/html/eduTrac/index.php(27): include('/var/www/html/e...')\n#8 {main}\n  thrown in /var/www/html/eduTrac/app/src/Core/Cache/etsis_Cache_Filesystem.php on line 166`"</p>
</details>
<br/>
<p>
same result if I do a
> chown -R www-data:www-data /var/www/etsis_tmp/
</p>

**Comment by nomadicjosh** [comment]
Your edit isn't correct. You have encased the directory in _ini_get()_. Look back at my example to see the difference between the two.

**Comment by planart** [comment]
Very Thanks
My mistake was the supposition that I did it right ;-)
Now it work like a charm
Good work Parker, thanks again

**Comment by nomadicjosh** [comment]
You are welcome.
