### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by asmeyb** [parkerj/eduTrac-SIS#65]
I use windows 10 
When I tried to run this command ./etsis core migrate it prompts me an error
please help me anyone how to fix this issue

**Comment by nomadicjosh** [comment]
Do you have [Cygwin](https://www.edutracsis.com/kb/command-line/) installed? Have you checked out the forums [here](https://www.edutracsis.com/forums/topic/cant-get-past-core-migrate-during-install/) or [here](https://www.edutracsis.com/forums/topic/error-after-etsis-core-migrate/)?

**Comment by asmeyb** [comment]
Yes I have installed cygwin but it does not  understand the command(./etsis
core migrate)

$ ./etsis core migrate
'.' is not recognized as an internal or external command,
operable program or batch file.



If you can get Graphical manual please attach to me

**Comment by nicopotgieter** [comment]
I have exactly the same problem. When I execute $ ./etsis core install i get 
This command has been removed and replaced with: ./etsis core migrate

I can execute may others, but when doing migrate I get the error

**Comment by nomadicjosh** [comment]
So `./etsis core migrate` does not work for you?

**Comment by nicopotgieter** [comment]
No

I have tried many variations but just can’t past it

**Comment by manju6** [comment]
I use windows 10, this command ./etsis core migrate will throw the below error.
$ ./etsis core migrate
'.' is not recognized as an internal or external command,
operable program or batch file.

Fix:
Copy the files in C:\wamp64\www\edutrac\app to C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\db

Edit the db name,username,password in the file C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\phinx.yml

Run C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\phinx.bat in windows.

Above action is similar to ./etsis core migrate
