### ISSUE TITLE
EDUTRAC 6.3.4 INSTALLATION ERROR 

### ISSUE THREAD

**Issue by ngnzone** [parkerj/eduTrac-SIS#66]
HELLO EVERYONE , I AM NEW TO edutrac. I have set it up on UBUNTU 16, php 7 mysql server 5.7.21. Apache2 server 
when I try to install after creating the DB and editing the config file, I get the following error. Please help point me to where I am missing out. thanks
Also when I go to app/tmp/logs I find just a index.html which says Directory access is forbidden. So I don't what to do next. I have changed the permissions with chmod 777  -R * but nothing seems to change.

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/rlde.data.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/rlde.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /var/www/html/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/alst.data.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/alst.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /var/www/html/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/stld.data.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/stld.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /var/www/html/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/clvr.data.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/clvr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /var/www/html/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/rrsr.data.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_put_contents(/var/lib/php/sessions/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 66

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: array_keys() expects parameter 1 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Config.php on line 42

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/Validate.php on line 132

Warning: file_get_contents(/var/lib/php/sessions/www/nodes/etsis/rrsr.config.node): failed to open stream: No such file or directory in /var/www/html/edutrac/app/src/Core/NodeQ/Helpers/File.php on line 61

Warning: Invalid argument supplied for foreach() in /var/www/html/edutrac/app/src/Core/NodeQ/CoreDatabase.php on line 141

Fatal error: Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /var/www/html/edutrac/config.php:104 Stack trace: #0 /var/www/html/edutrac/config.php(104): PDO->__construct('mysql:host={hos...', '{username}', '{password}', Array) #1 /var/www/html/edutrac/Liten/Helper/Set.php(212): {closure}(Object(Liten\Helper\Set)) #2 /var/www/html/edutrac/Liten/Helper/Set.php(76): Liten\Helper\Set->Liten\Helper\{closure}(Object(Liten\Helper\Set)) #3 /var/www/html/edutrac/Liten/Liten.php(126): Liten\Helper\Set->get('db') #4 /var/www/html/edutrac/app/src/Hooks.php(814): Liten\Liten->__get('db') #5 /var/www/html/edutrac/app/functions/logger-function.php(74): app\src\Hooks->get_option('system_email') #6 /var/www/html/edutrac/app/functions/dependency.php(693): require('/var/www/html/e...') #7 /var/www/html/edutrac/config.php(117): require('/var/www/html/e...') #8 /var/www/html/edutrac/index.php(27): include('/var/www/html/e...') #9 {main} Next PDOException: SQLSTATE[HY000] [ in /var/www/html/edutrac/config.php on line 104
Also when I go to app/tmp/logs I find just a index.html which says Directory access is forbidden. So I don't what to do next. I have changed the permissions with chmod 777  -R * but nothing seems to change.

**Comment by manju6** [comment]
Create Folders manually in the respective location.
