### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by BereaSchool** [parkerj/eduTrac-SIS#67]
I have attempted to access our etSIS through multiple browsers, and I continue to get the error message of an expired certificate.  Is the problem on my end?

**Comment by BereaSchool** [comment]
Here's the screenshot.[](url)
![screen shot 2018-05-07 at 4 33 41 pm](https://user-images.githubusercontent.com/35111092/39723672-8d7ba222-5214-11e8-8d6b-1f836991b89c.png)

**Comment by nomadicjosh** [comment]
Sorry. For some reason it didn't automatically renew. This should be fixed now.

**Comment by BereaSchool** [comment]
Thank you!!
