### ISSUE TITLE
problem in installing Edutrac

### ISSUE THREAD

**Issue by mhussamkh** [parkerj/eduTrac-SIS#68]
when following the instructions in https://www.edutracsis.com/kb/installation/
once apply the command: ./etsis core migrate
the following error: sh: 1: ./phinx: not found

PS I am using LAMP 7.0.30-0

**Comment by nomadicjosh** [comment]
Does the file ```phinx``` exist in the root where the other files are?

**Comment by mhussamkh** [comment]
yes and the command chmod +x phinx already executed

**Comment by nomadicjosh** [comment]
What is in your server's error logs about this error?

**Comment by manju6** [comment]
I use windows 10, this command ./etsis core migrate will throw the below error.
$ ./etsis core migrate
'.' is not recognized as an internal or external command,
operable program or batch file.

Fix:
Copy the files in C:\wamp64\www\edutrac\app to C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\db

Edit the db name,username,password in the file C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\phinx.yml

Run C:\wamp64\www\edutrac\app\src\vendor\robmorgan\phinx\bin\phinx.bat in windows.

Above action is similar to ./etsis core migrate
