### ISSUE TITLE
eduTrac-SIS.6.3.4-Stable is not installing succssfully

### ISSUE THREAD

**Issue by amitjhagithub** [parkerj/eduTrac-SIS#74]
Hi,

I followed this guide this https://www.edutracsis.com/kb/installation/ to install app but no luck. 

Please check the screenshot of executed command. 

http://prntscr.com/k38ncu

I have vps server. I renamed "config.sample.php" to "config.php" and "phinx.sample.php" to "phinx.php". Added database info in phinx.php and then ran command through ssh. 

When i check database only 4 table created.  Error log file showing some error. here the error.

[06-Jul-2018 09:51:15 UTC] PHP Fatal error:  Uncaught PDOException: PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/acmainsis/public_html/eduTrac/config.php:104
Stack trace:
#0 /home/acmainsis/public_html/eduTrac/config.php(104): PDO->__construct('mysql:host={hos...', '{username}', '{password}', Array)
#1 /home/acmainsis/public_html/eduTrac/Liten/Helper/Set.php(212): {closure}(Object(Liten\Helper\Set))
#2 /home/acmainsis/public_html/eduTrac/Liten/Helper/Set.php(76): Liten\Helper\Set->Liten\Helper\{closure}(Object(Liten\Helper\Set))
#3 /home/acmainsis/public_html/eduTrac/Liten/Liten.php(126): Liten\Helper\Set->get('db')
#4 /home/acmainsis/public_html/eduTrac/app/src/Hooks.php(814): Liten\Liten->__get('db')
#5 /home/acmainsis/public_html/eduTrac/app/functions/logger-function.php(74): app\src\Hooks->get_option('system_email')
#6 /home/acmainsis/public_html/eduTrac/app/functions/dependency.php(693): require('/home/acmainsis...')
#7 /home/acmainsis/public_html/eduTrac/config.php(117): require('/home/acmain in /home/acmainsis/public_html/eduTrac/config.php on line 104

Please help.

**Comment by nomadicjosh** [comment]
I can't see the full error message that I need to see in your screenshot. Also, during installation, you are to only rename phinx.sample.php to phinx.php. The installer takes care of the config file.

**Comment by amitjhagithub** [comment]
Ok, There is not error during installation.  except one db error. When i check database only 4 table created and after installation i run my site it give http error 500. u can check here. 

http://acmainsis.com/eduTrac/

Please let me know what's issue.

**Comment by amitjhagithub** [comment]
Also, only initiallySchema: migration message on command prompt. u can see in screenshot. 

http://prntscr.com/k38ncu

**Comment by nomadicjosh** [comment]
I need to see the full error message. Your screenshot is cutting off some of the error message. I need to know what the full message is for `Field 'grsc' doesn't have .....`

**Comment by amitjhagithub** [comment]
ok here full screenshot

http://prntscr.com/k3alcl

**Comment by nomadicjosh** [comment]
It's because of a strict mode setting for mysql. The below link should be of help:

https://stackoverflow.com/questions/15438840/mysql-error-1364-field-doesnt-have-a-default-values
