### ISSUE TITLE
Just looked at my Error log. Is any of this normal?

### ISSUE THREAD

**Issue by speckergdh** [parkerj/eduTrac-SIS#76]
I have this error every couple of seconds in my install? Is this normal?

E_WARNING,"file_get_contents(/var/cpanel/php/sessions/ea-php72/www/nodes/etsis/student_email.config.node):   failed to open stream: No such file or   directory","/home/acmainsis/public_html/app/src/Core/NodeQ/Helpers/File.php","61",""
--

**Comment by nomadicjosh** [comment]
What release did you install?

**Comment by speckergdh** [comment]
The current version

**Comment by nomadicjosh** [comment]
If you open the RELEASE file in a text editor, it will show the release value.

**Comment by speckergdh** [comment]
6.3.4

**Comment by nomadicjosh** [comment]
Ok, have you checked out [Cookies and File Savepath](https://www.edutracsis.com/kb/installation/#Cookies_and_File_Savepath) section?
