### ISSUE TITLE
i am very angry

### ISSUE THREAD

**Issue by gsons** [parkerj/eduTrac-SIS#81]
i am very angry
i can't see anything when i open home page,it show blank
could everyone help me to solve the problem?i will thank you

**Comment by nomadicjosh** [comment]
Have you checked out your error logs? Did you check out [troubleshooting](https://www.edutracsis.com/kb/troubleshooting/)? Did you check out [debugging](https://www.edutracsis.com/wiki/debugging-edutrac-sis/)?
