### ISSUE TITLE
System Module

### ISSUE THREAD

**Issue by jacksaaa** [parkerj/eduTrac-SIS#82]
where can I contact the support from the site I have an Issue with Modules.

**Comment by nomadicjosh** [comment]
I am assuming you are referring to the payment link. Did it not appear in your inbox or spam folder?

**Comment by jacksaaa** [comment]
no, I didn't receive any email. Can you help with that plz?

**Comment by nomadicjosh** [comment]
Are you using the gmail account or outlook account. I suggest using the gmail account, and then you should be able to receive the email.

**Comment by jacksaaa** [comment]
am using the Gmail account, and nothing in there.

**Comment by jacksaaa** [comment]
can you send the link to my gmail account plz? 

thanks a lot.

**Comment by nomadicjosh** [comment]
Closing since this was concluded over email.
