### ISSUE TITLE
"Create section" on course lookup "action" button

### ISSUE THREAD

**Issue by Tejamvn** [parkerj/eduTrac-SIS#83]
Hi,
In the previous versions, there would be a "create section" on course lookup screen with other options like "view", "clone" and "create section". Now I couldn't see it on the list all i can see are "view" and "clone". I thought that was taken down during an update. 
But when i checked the code on "course/index.php" it is still there in the list. Is it the bug or really was taken down?
![capture1](https://user-images.githubusercontent.com/26163055/48776835-ca830a80-ecc8-11e8-9250-91617fe062e9.PNG)

![capture](https://user-images.githubusercontent.com/26163055/48776724-7d069d80-ecc8-11e8-83ed-d4fe1b1696a5.PNG)

**Comment by nomadicjosh** [comment]
I will take a look, but I think this is an issue of when you are not looking up a specific course.

**Comment by Tejamvn** [comment]
I tried that as well(looking for a specific course) and still got the same. I looked at demo edutrac site [here](https://630.etsis.us/crse/), well it might be a different version I am not really sure, but it had the "course section" button.

**Comment by nomadicjosh** [comment]
In course/index.php, change this:

```
<?php if(_h($v['currStatus']) == _t( 'A' ) && _h($v['endDate']) == '0000-00-00') : ?>
<li<?=ae('add_course_sec');?>><a href="<?=get_base_url();?>sect/add/<?=_h($v['courseID']);?>/"><?=_t( 'Create Section' ); ?></a></li>
<?php endif; ?>
```

to this:

```
<?php if(_h($v['currStatus']) == _t( 'A' ) && _h($v['endDate']) <= '0000-00-00') : ?>
<li<?=ae('add_course_sec');?>><a href="<?=get_base_url();?>sect/add/<?=_h($v['courseID']);?>/"><?=_t( 'Create Section' ); ?></a></li>
<?php endif; ?>
```
