### ISSUE TITLE
Multiple Errors 

### ISSUE THREAD

**Issue by jacksaaa** [parkerj/eduTrac-SIS#84]
When I but the system in DEV mode I get this errors. 

what is the issue you think? 
![error 1](https://user-images.githubusercontent.com/29363043/49150005-478b3100-f314-11e8-9a60-3575e5bdd537.png)

**Comment by nomadicjosh** [comment]
What ever you've set as the [cookies and file savepath](
https://www.edutracsis.com/kb/installation/#Cookies_and_File_Savepath), the system doesn't have write permission to it, so it can't create the needed files.

**Comment by jacksaaa** [comment]
I created the file my self and it works fine 👍
