### ISSUE TITLE
Can not get pass offline page

### ISSUE THREAD

**Issue by onostboy** [parkerj/eduTrac-SIS#85]
I installed edutrac sis on my localhost, i edited the config.php file according to my database info but after launching  "localhost/edutrac", i get redirected to an offline page which says "**Please excuse the dust. We are giving the portal a new facelift. Please try back again in an hour**".  I am totally lost from here and don't know what to do, i am using this edutrac sis as a project in school which is to be submitted soon. Any help will be highly appreciated

**Comment by nomadicjosh** [comment]
Check out [Offline Mode](https://www.edutracsis.com/kb/troubleshooting/#Offline_Mode) in the docs.

**Comment by onostboy** [comment]
![error](https://user-images.githubusercontent.com/45664421/49638766-7cc90a80-fa09-11e8-84e0-2f4418d1e20e.PNG)
After Checking the offline mode docs, i could not find anything like " Screens > Administrative > General Settings " on the software. A picture of the error i am getting is attached here

**Comment by nomadicjosh** [comment]
It's in the general settings. You can't change anything unless you are logged in. Once logged in, then proceed to the Dashboad and you will see several menus.

**Comment by onostboy** [comment]
I finally found a way to login with a default username and passowrd provided in the docs but all i am getting is "404 error" whenever i click the Dashboard and no general settings options. 
![404 error](https://user-images.githubusercontent.com/45664421/49719707-3c15ff00-fc5e-11e8-8fdb-6e3b3291ce21.PNG)

**Comment by nomadicjosh** [comment]
Does a .htaccess file exist in the root?

**Comment by onostboy** [comment]
Yes sir, i have htaccess file 
![htaccess](https://user-images.githubusercontent.com/45664421/49789356-15be9500-fd2c-11e8-8ab0-08940c35e2c0.PNG)

**Comment by abubaker-hmd** [comment]
can you please tell me the step to install edutrac on my wamp 
any help or guiding will be mush appreciated 
because i keep getting theses error 
![errr](https://user-images.githubusercontent.com/17971121/50042817-90135000-0071-11e9-8a56-fd3a574987ee.PNG)
Thank you

**Comment by nomadicjosh** [comment]
Follow the link below for fix:

[https://github.com/parkerj/eduTrac-SIS/issues/84#issuecomment-442453388](https://github.com/parkerj/eduTrac-SIS/issues/84#issuecomment-442453388)

**Comment by kharrisbsu** [comment]
I have followed all these posts and tried on my local host as well but I can not seem to find the default user name and password. Can someone please help me.
