### ISSUE TITLE
Problem with adding in Billing Table

### ISSUE THREAD

**Issue by abubaker-hmd** [parkerj/eduTrac-SIS#86]
I Hope you can help me out or guide me and thank you in advance 
i keep getting conflict when ever i try to add a bill in Billing Table
and even when i open the page /financial/billing-table/
in the Error Log i get 

_WARNING	A non-numeric value encountered	/home/hope/public_html/app/views/financial/gl-summary.php line	87	
E_WARNING	A non-numeric value encountered	/home/hope/public_html/app/views/financial/gl-summary.php line	88	
E_WARNING	A non-numeric value encountered	/home/hope/public_html/app/views/financial/gl-summary.php line	88	
E_WARNING	Invalid argument supplied for foreach()	/home/hope/public_html/app/functions/student-function.php line	544	
E_WARNING	implode(): Invalid arguments passed	/home/hope/public_html/app/views/student/add.php line	16
![open table](https://user-images.githubusercontent.com/17971121/50042393-d913d600-006a-11e9-8ffe-220df65bee84.PNG)
![when i try to save a bill](https://user-images.githubusercontent.com/17971121/50042394-d913d600-006a-11e9-84b8-cfcbe0504f0a.PNG)

the fist images when i open the page 
the second images when i try to save a bill

**Comment by jacksaaa** [comment]
Dear, Parker

any update about this issue ??

**Comment by nomadicjosh** [comment]
What PHP version are you using?

**Comment by abubaker-hmd** [comment]
PHP version 7.1

**Comment by nomadicjosh** [comment]
What release of eduTrac SIS do you have installed?

**Comment by abubaker-hmd** [comment]
Release 6.3.4

**Comment by nomadicjosh** [comment]
I can't reproduce those errors. Can you tell me step by step how you installed the system?

**Comment by abubaker-hmd** [comment]
Download the moodle 
uploaded it to our server(VPS) and unpack it 
log throw the ssh
create the database 
migrate the database
alter the config file(database connection part)
I think that's about it 
Thank you

**Comment by nomadicjosh** [comment]
And there was no error message when you migrated the database?

How many tables are in your database?

Are there any plugins activated? If so, deactivate them and see if the issue remains.

**Comment by abubaker-hmd** [comment]
Hello  Mr.Parker 
Done All that with no success bill insertion
and i have 94 table in my db

**Comment by abubaker-hmd** [comment]
Mr.Parker ??!

**Comment by nomadicjosh** [comment]
I think there are supposed to be 95 tables. You can use this [list](https://keybase.pub/joshuaparker/etsis_test.sql) to check which table you are missing.

**Comment by abubaker-hmd** [comment]
attendance is the missing table 
does it effect in this case??

**Comment by nomadicjosh** [comment]
No, but you should add it nonetheless. I will have to add a fix for the financial module based on the changes to php 7.1.x.

**Comment by abubaker-hmd** [comment]
Okay thank you, will do 
Yes please that will be great 
thank you anyway

**Comment by abubaker-hmd** [comment]
Hello again
i was wondering what is the php version that you are using so i can test it??
thank you

**Comment by nomadicjosh** [comment]
Everything works on PHP 7.0.
