### ISSUE TITLE
Problem Adding New Student and Registering for Courses

### ISSUE THREAD

**Issue by kevindionr** [parkerj/eduTrac-SIS#87]
So my problem is two-fold. 

After I have added a student from creating a person, and then creating an application, when I go to student lookup, the list is still empty. Shows no students. 

Second problem is when I attempt to add a student under course registration, when I put in the student ID number, there is no dropdown box that appears with their name. And even when I submit it with just the typed ID number, it says ID number must be numeric.

**Comment by abubaker-hmd** [comment]
After your make the student application 
you go here as in below 
![screenshot_20181227150518](https://user-images.githubusercontent.com/17971121/50481227-153f2300-09e9-11e9-86c9-cd87275a032f.png)
 the image  

enter the student id or name 
in the drop arrow you click on create student 
Hope that help

**Comment by kevindionr** [comment]
When I got to that screen, the "Advisor" field is mandatory but there is no where for me to enter advisors names. [
<img width="1680" alt="screen shot 2018-12-27 at 8 54 18 am" src="https://user-images.githubusercontent.com/46090321/50482564-37b74900-09b5-11e9-9196-8970e79ff023.png">
](url)

**Comment by abubaker-hmd** [comment]
To make adviser position 
in person->add person ->the PERSON TYPE is fac Faculty and PERSON ROLE is Faculty save it
search the person lookup with the adviser name or id you gave 
when you find it in the arrow down select create staff record you fill the form 
that's about it

**Comment by kevindionr** [comment]
Thank you I got it done :-)
