### ISSUE TITLE
Transcript Default Design

### ISSUE THREAD

**Issue by kevindionr** [parkerj/eduTrac-SIS#88]
Is there a way to change the default design of the transcript?

**Comment by nomadicjosh** [comment]
This is probably what you are looking for: [https://www.edutracsis.com/kb/custom-transcript/](https://www.edutracsis.com/kb/custom-transcript/)

**Comment by kevindionr** [comment]
I saw this link but I am not good with technology. If I buy the eduTrac SIS Premium subscription, would that include having a custom transcript set up?

**Comment by nomadicjosh** [comment]
No, customizations are not available through any of the subscriptions. If you post to the [forums](https://www.edutracsis.com/forums/forum/product-support/how-to-and-troubleshooting/) what you are looking for, I can try to help get you there.

**Comment by kevindionr** [comment]
Ok thanks I have posted in the forum.
