### ISSUE TITLE
Degree Audit/Academic Progress Tracker

### ISSUE THREAD

**Issue by kevindionr** [parkerj/eduTrac-SIS#91]
Is there a degree audit or academic progress tracker? Something that has the capability to see how far students are along in a degree program and what courses they need to complete etc..?

**Comment by nomadicjosh** [comment]
No, not yet. Haven't found a way to do it well as of yet.

**Comment by nomadicjosh** [comment]
A separate project has been created for this: [Degree Audit](https://github.com/parkerj/eduTrac-SIS/projects/1)
