### ISSUE TITLE
What permissions are needed in order to Withdraw or Drop a student from a course?

### ISSUE THREAD

**Issue by kevindionr** [parkerj/eduTrac-SIS#94]
I have super administrator status and I still can't withdraw or drop a student from a course? How do I do that?

**Comment by nomadicjosh** [comment]
You go to the student's SPRO screen, then click on STAC. On the next screen will be a list of the student's courses. Under the Actions column, click on the blue arrow and the click on View SACD. On the SACD screen, you should change the Status to D, and click save.

**Comment by kevindionr** [comment]
I have done that but it only gives me the option to Cancel and not an option to Save. I think there must be something missing in my permissions that is causing this error.

**Comment by nomadicjosh** [comment]
If you've set Inquiry only permissions, you won't be able to save on some screens. They should be removed from the Super Administrator role. Inquiry only is restrictive.
