### ISSUE TITLE
booking module

### ISSUE THREAD

**Issue by seeyer** [parkerj/eduTrac-SIS#95]
hi josh. i noticed something with the installed modules, i have the booking module 1.1.2 and a couple of more installed but when i create a course section i cant create timetable for it, the booking control is the but the is no save button meaning i cant save my timetable selection. i do not know if am doing something wrong or i need to get the modules bundle before this functionality can actually work.
any assistance will be appreciated.
thanks

**Comment by nomadicjosh** [comment]
Are you logged in with the super administrator role? If so, make sure that none of the _inquiry only_ permissions have been added to the role.

**Comment by seeyer** [comment]
i implemented the changes and its working perfectly fine. thanks a lot and remain blessed.

**Comment by nomadicjosh** [comment]
You are welcome.

**Comment by seeyer** [comment]
hi josh, quick one! when i add a new person manually and enable the send username and password to user it actually shows successful message sent to queue but the login  details isn't  sent to the user email. please any help on this will be appreciated. 
Then  again i started experiencing  a 504 error while trying to open the " applicant" and  "person name and address"  page. i at first thought is was network or maybe a corrupt database but i ran a database check/repair and it came back positive i.e database perfectly OK. please any assistance on how to troubleshoot further will be appreciated because i cant create student at the moment thanks.
