### ISSUE TITLE
Bug Email Cornjob handlers register 

### ISSUE THREAD

**Issue by ahmed264** [parkerj/eduTrac-SIS#96]
i install edutrac 6.3.4
in config crontab on server and put only this command
* * * * * /usr/bin/curl -s http://10.40.40.200/eduTrac-SIS/cron/cronjob?password=XXX
and config system in cronjob handlers all cronjob

the issue email not sent
and crontab 
Running: http://10.40.40.200/eduTrac-SIS/cron/runEmailQueue/

Connecting to cronjob

**Comment by nomadicjosh** [comment]
What is the status of the campaign?
