### ISSUE TITLE
SMPT plugin installed but fails to send email 

### ISSUE THREAD

**Issue by seeyer** [parkerj/eduTrac-SIS#97]
hi josh, quick one! when i add a new person manually and enable the send username and password to user it actually shows successful message sent to queue but the login details isn't sent to the user email. please any help on this will be appreciated.

**NOTE:**  when applicant signup or register it sends their username / password successfully  but when i add a new person as an admin it doesn't send them login details  

Then again i started experiencing a 504 error while trying to open the " applicant" and "person name and address" page. i at first thought is was network or maybe a corrupt database but i ran a database check/repair and it came back positive i.e database perfectly OK. please any assistance on how to troubleshoot further will be appreciated because i cant create student at the moment thanks.

**Comment by nomadicjosh** [comment]
Are there any errors in your server's log or etSIS error logs that may give a clue to the issue? Also, when checking that button to send an email, check to make sure that the queue has been populated after hitting the submit button to save the new NAE record.

**Comment by seeyer** [comment]
yes please  i found this on the etSIS error logs: 

"
Error | 212.103.50.246 |   | (70007)The timeout specified has expired: AH01075: Error dispatching request to :, referer: http://portal.************/dashboard/ |   |   |   | Apache error

and 

Error | 212.103.50.246 | 503 | GET /appl/ HTTP/1.0.

I think i need to increase the timeout but i dont know how to go about it......"

kind regards

**Comment by nomadicjosh** [comment]
Never saw this message. It is something you can change in your apache directive or something you can add to .htaccess.

[.htaccess](https://stackoverflow.com/questions/9629566/how-to-increase-apache-timeout-directive-in-htaccess)

[Apache Directive](https://unix.stackexchange.com/questions/270655/how-to-find-and-edit-apache-timeout)
